cdnaref: "Homo_sapiens.GRCh38.cdna.all.fa"

genomeref: "hg38.fa"

annotation: "Homo_sapiens.GRCh38.95.gtf.gz"

fastq:
- "fastq1"
- "fastq2"

region_of_interest:

maximum_secondary: 100

secondary_score_ratio: 1.0

threads: 50

outputdir: "dir "
